{
 "title": "Powerwall",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Load Power",
     "measurement": "http",
     "select": [
      [
       { "params": [ "load_instant_power" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Solar Power",
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery Power",
     "measurement": "http",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PGE Power",
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Solar Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PGE Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PGE Power",
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "load_instant_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Offset",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Solar Generated",
     "measurement": "http",
     "query": "SELECT INTEGRAL(\"solar_instant_power\", 1h) FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "solar_energy_exported" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PGE Generated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT INTEGRAL(\"site_instant_power\", 1h) FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Solar Power Generated Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT MAX(\"solar_instant_power\") FROM \"http\" WHERE time >= now() - 12h",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Solar Power Generated in 7d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT MAX(\"solar_instant_power\") FROM \"http\" WHERE time >= now() - 7d",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}